version: '3'

tasks:
  build-polite-lib:
    cmds:
      - |
        rm -rf /opt/homebrew/lib/python3.11/site-packages/polite_lib*
        rm -rf src/polite_lib.egg-info
        cd src
        rm -rf build/
        rm -rf dist/
        # pip install .
        python3 setup.py install
        rm -rf build/
        rm -rf dist/
        rm -rf src/polite_lib.egg-info
  remove-polite-lib:
    cmds:
      - |
        rm -rf /opt/homebrew/lib/python3.11/site-packages/polite_lib*
        rm -rf src/polite_lib.egg-info
