version: '3'

tasks:
  build-polite-lib:
    cmds:
      - |
        rm -rf /opt/homebrew/lib/python3.11/site-packages/polite-lib*
        rm -rf /opt/homebrew/lib/python3.11/site-packages/polite-lib*
        cd src
        python3 setup.py build
        python3 setup.py install
        rm -rf build/
        rm -rf dist/
        rm -rf polite_lib.egg-info/
