version: '3'

tasks:
  build:
    cmds:
      - |
        rm -rf /opt/homebrew/lib/python3.10/site-packages/polite_lib*
        rm -rf src/polite_lib.egg-info
        cd src
        rm -rf build/
        rm -rf dist/
        python3.10 -m pip install .

  remove:
    cmds:
      - |
        rm -rf /opt/homebrew/lib/python3.11/site-packages/polite_lib*
        rm -rf src/polite_lib.egg-info
  test:
    cmds:
      - task: build
      - |
        pytest -s --cov=polite_lib tests/unit

  pre-commit:
    cmds:
      - task: build
      - task: test
      - |
        echo "pre-commit passed!"
    silent: true

  # activate-env:
  #   cmds:
  #     - |
  #       source plib/bin/activate
