name: Validate

on:
  push:
    branches: ["stage"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      credentials:
        username: ${{ vars.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Build Polite-Lib
        run: |
          echo "Run Build"
          echo "WHO AM I: $(whoami)"
          cd src/
          python3 setup.py build
          python3 setup.py install 

      - name: Run Unit Tests
        run: |
          pip install -r tests/requirements.txt
          pytest tests/unit

# End File: polite-lib/.github/workflows/validate.yaml
