name: Validate

on:
  push:
    branches: ["stage"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      credentials:
        username: ${{ vars.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python 3.10
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        if: steps.changes.outputs.src == 'true'
        run: |
          python3 -m pip install --upgrade pip
          pip install -r src/requirements.txt

      # - name: Build Container
      #   run: |
      #     echo "Run Build"
      #     python3 -m pip install --upgrade pip
      #     pip install -r src/requirements.txt
      # - name: Push Container
      #   run: |
      #     cd tests/
      #     pip install -r requirements.txt
      #     pytest unit

# End File: polite-lib/.github/workflows/validate.yaml
