name: Validate

on:
  push:
    branches: ["stage"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      credentials:
        username: ${{ vars.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: docker/login-action@v2
        with:
          registry: harbor.squid-ink.us
          username: ${{ vars.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build Container
        run: |
          echo "Run Build"
          cd src
          pip install -r requirements.txt
          pi3 install .
      - name: Push Container
        run: |
          cd tests/
          pip install -r requirements.txt
          pytest unit

# End File: polite-lib/.github/workflows/validate.yaml
